Console.WriteLine("Введите номер дня недели от 1 до 7");
int a = Convert.ToInt32(Console.ReadLine());
if (a == 1) Console.Write("Понедельник");
else if (a == 2) Console.Write("Вторник");
else if (a == 3) Console.Write("Среда");
else if (a == 4) Console.Write("Червер");
else if (a == 5) Console.Write("Пятница");
else if (a == 6) Console.Write("Суботта");
else if (a == 7) Console.Write("Воскресенье");
else Console.Write("Вы ввели не верный номер дня недели");